version: "3"
services:
  mysql:
    environment:
        DATABASE_DRIVER:
        DATABASE_NAME:
        DATABASE_USER:
        DATABASE_PASSWORD:
        DATABASE_HOST:
        DATABASE_PORT:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=gowebskel
        - MYSQL_USER=gowebskel
        - MYSQL_PASSWORD=gowebskel
